[default_session]
startup_command = "tx start dev path={} --append && tmux kill-window -t 1"
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "Dotfiles"
path = "~/.dotfiles"

[[session]]
name = "Downloads"
path = "~/Downloads"
