git:
  overrideGpg: true
  paging:
    colorArg: always
    pager: delta --paging=never
customCommands:
  - key: "<c-p>"
    command: "git fetch --prune"
    context: "localBranches"
    description: "Prune local branches"
    output: log
