#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'diamond'
    leading_diamond = ''
    trailing_diamond = ''
    template = '  {{ path .Path .Location }} '
    background = 'blue'
    foreground = 'transparent'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      style = 'agnoster_short'
      max_depth = 3

  [[blocks.segments]]
    type = 'git'
    style = 'diamond'
    trailing_diamond = ''
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}transparent{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}transparent{{ end }}', '{{ if gt .Ahead 0 }}transparent{{ end }}']
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}yellow{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}red{{ end }}', '{{ if gt .Ahead 0 }}#49416D{{ end }}', '{{ if gt .Behind 0 }}#7A306C{{ end }}']
    template = ' {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ end }}{{ if .Staging.Changed }}  {{ end }}'
    background = 'cyan'
    foreground = 'transparent'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      branch_max_length = 25
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    type = 'status'
    style = 'diamond'
    background_templates = ['{{ if gt .Code 0 }}red{{ end }}']
    trailing_diamond = ''
    template = ' {{ if gt .Code 0 }}{{ else }}{{ end }} '
    background = 'green'
    foreground = 'transparent'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      always_enabled = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    type = 'node'
    style = 'plain'
    template = ' '
    background = 'transparent'
    foreground = 'green'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_package_manager = false
      home_enabled = false

  [[blocks.segments]]
    type = 'go'
    style = 'plain'
    template = ' '
    background = 'transparent'
    foreground = 'blue'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    type = 'rust'
    style = 'plain'
    template = "  {{ .Full }} "
    background = 'transparent'
    foreground = 'red'
    Text = ''
    Duration = 0
    NameLength = 0

  [[blocks.segments]]
    type = 'python'
    style = 'plain'
    template = "  {{ .Full }} "
    background = 'transparent'
    foreground = 'yellow'
    Text = ''
    Duration = 0
    NameLength = 0

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    foreground = 'magenta'
    template = '❯'


[transient_prompt]
  template = '❯ '
  background = 'transparent'
  foreground = 'magenta'
  Text = ''
  Duration = 0
  NameLength = 0
